export default [
  {
    params: { resources: 'resources-ia' },
    props: {
      title: 'JaviRecursos | Inteligencia Artificial',
      description:
        'En este apartado de la web JaviResources, podrás conseguir herramientas de Inteligencia Artificial que ayuden tu dia a dia como desarrollador o diseñador.',
      keywords: [
        'Inteligencia Artificial',
        'Recursos de inteligencia artificial',
        'Herramientas de inteligencia artificial',
        'IA',
        'JaviRecursos | Inteligencia Artificial',
        'JaviRecursos',
      ],
      id: 'IA',
      category: true,
      resources: {
        Chat: [
          {
            name: 'Chat GPT',
            des: 'ChatGPT es una aplicación de chatbot de inteligencia artificial desarrollado en 2022 por OpenAI que se especializa en el diálogo. El chatbot es un modelo de lenguaje ajustado con técnicas de aprendizaje tanto supervisadas como de refuerzo.',
            url: 'https://openai.com/chatgpt',
            category: 'Chat',
            id: 'IA-1',
          },
          {
            name: 'Perplexity',
            des: 'Perplexity también denominado Perplexity AI, es un motor de búsqueda impulsado por inteligencia artificial que utiliza grandes modelos de lenguaje para proporcionar respuestas precisas a preguntas complejas.',
            url: 'https://www.perplexity.ai/',
            category: 'chat',
            id: 'IA-2',
          },
        ],
        Images: [
          {
            name: 'Midjourney',
            des: 'Midjourney es un laboratorio independiente de investigación y el nombre de un programa de inteligencia artificial con el cual sus usuarios pueden crear Imágenes a partir de descripciones textuales, similar a Dall-e de OpenAI y al Stable Diffusion de código abierto',
            url: 'https://www.midjourney.com/',
            category: 'Images',
            id: 'IA-3',
          },
        ],
        Audio: [
          {
            name: 'Beatoven.ai',
            des: 'Crea música de fondo libre de derechos de autor con el poder de la IA. Recomendado para vídeos, podcasts y juegos. ¡Pruébalo ahora!',
            url: 'https://www.beatoven.ai/',
            category: 'Audio',
            id: 'IA-4',
          },
        ],
        Website: [
          {
            name: 'Devi AI',
            des: 'Con esta herramientas, puede crear una pagina web en menos de 30seg y totalmente gratis.',
            url: 'https://website.ddevi.com/',
            category: 'Website',
            id: 'IA-6',
          },
          {
            name: 'Durable',
            des: 'Ponga su negocio en línea en 30 segundos con el creador de sitios web y la plataforma de marketing AI nº 1.',
            url: 'https://es.durable.co/',
            category: 'website',
            id: 'IA-7',
          },
        ],
      },
    },
  },
  {
    params: { resources: 'courses' },
    props: {
      title: 'JaviRecursos | Cursos de programación, desarrollo web y mas',
      description:
        'En este apartado de la web JaviRecursos, conseguirás algunos cursos de lenguajes de programación, framework y entre otros temas mas centrado en el desarrollo web y la programación.',
      keywords: [
        'Cursos de desarrollo web',
        'JaviRecursos | Cursos de programación y desarrollo web',
        'cursos de programación',
        'Cursos de framework',
      ],
      id: 'cursos',
      category: true,
      resources: {
        Frontend: [
          {
            name: 'Curso HTML & CSS (1 / 5): Fundamentos HTML - jonmircha',
            des: 'En este curso te enseño los fundamentos de HTML, el lenguaje de marcado que define el contenido en la web.',
            url: 'https://www.youtube.com/watch?v=-oK6zL01fNM&t=10681s',
            category: 'Frontend',
            id: 'C-1',
          },
          {
            name: 'Curso HTML & CSS (2 / 5): Fundamentos CSS - jonmircha',
            des: 'En este curso te enseño los fundamentos de CSS, el lenguaje que define la presentación del contenido en la web.',
            url: 'https://www.youtube.com/watch?v=K3xmRF8ab1o&t=12s',
            category: 'Frontend',
            id: 'C-2',
          },
          {
            name: 'Curso HTML & CSS (3 / 5): Unidades y Estilos CSS - jonmircha',
            des: 'En este curso te enseño las diferentes unidades de medida existentes en CSS y diferentes estilos que podemos aplicar a las etiquetas HTML.',
            url: 'https://www.youtube.com/watch?v=p_lT7AgpEMU&t=15829s',
            category: 'Frontend',
            id: 'C-3',
          },
          {
            name: 'Curso HTML & CSS (4 / 5): Efectos visuales y Movimientos CSS - jonmircha',
            des: 'En este curso te enseño a crear efectos visuales estáticos y con movimiento en CSS.',
            url: 'https://www.youtube.com/watch?v=mVhoGXkDbMw&t=24119s',
            category: 'Frontend',
            id: 'C-4',
          },
          {
            name: 'Curso HTML & CSS (4 / 5): Responsive Design y Arquitectura CSS - jonmircha',
            des: 'En este curso te enseño sobre Responsive Design y Arquitectura CSS.',
            url: 'https://www.youtube.com/watch?v=udGrXWeJp1Y&t=4963s',
            category: 'Frontend',
            id: 'C-5',
          },
        ],
        Programación: [
          {
            name: 'Curso de JavaScript',
            des: "Aprende JavaScript el lenguaje que domina la web: Sintaxis, Gramática, Lógica, EcmaScript, POO, Asincronía, DOM, AJAX, JSON, API's, Node y más.",
            url: 'https://www.youtube.com/playlist?list=PLvq-jIkSeTUZ6QgYYO3MwG9EMqC-KoLXA',
            category: 'Programación',
            id: 'C-6',
          },
          {
            name: 'Curso de Python',
            des: 'Python es el lenguaje de programación más popular de 2022. Este es un curso desde cero para principiantes creado para aprender los fundamentos desde su base.',
            url: 'https://www.youtube.com/watch?v=Kp4Mvapo5kc',
            category: 'Programación',
            id: 'C-7',
          },
          {
            name: 'Curso de fundamentos de programación & Java',
            des: 'El curso comienza enseñando programación desde cero. Posteriormente, se concentra en Java, pero también tiene como objetivo proporcionar una visión general para facilitar el aprendizaje de otros lenguajes.',
            url: 'https://www.youtube.com/playlist?list=PLG1qdjD__qH6ULjW5iN8E45m5nkaCNbUu',
            category: 'Programación',
            id: 'C-7',
          },
          {
            name: 'Programación en C++ || Programación ATS',
            des: 'Te gustaría aprender a programar en C++? Si es así, te recomiendo que revises este curso GRATUITO, un curso muy práctico donde aprenderás desde cero a programar en C++.',
            url: 'https://www.youtube.com/playlist?list=PLWtYZ2ejMVJlUu1rEHLC0i_oibctkl0Vh',
            category: 'Programación',
            id: 'C-8',
          },
        ],
        Diseño: [
          {
            name: 'Curso de figma',
            url: 'https://www.youtube.com/playlist?list=PLvq-jIkSeTUbpfewvbKLhHctdkgadAy-K',
            des: 'Aprende Figma la aplicación web que te permite crear diseños y prototipos de UI y UX.',
            category: 'Diseño',
            id: 'C-9',
          },
        ],
      },
    },
  },
  {
    params: { resources: 'resources-developer' },
    props: {
      title: 'JaviRecursos | Herramientas para desarrolladores',
      description: '',
      id: 'Developer',
      category: true,
      keywords: [
        'Herramientas para developer',
        'Recursos para developer',
        'dev',
        'desarrollador',
      ],
      resources: {
        HTML: [
          {
            name: 'Markup Validation Service',
            url: 'https://validator.w3.org/',
            id: 'Dev-1',
            category: 'HTML',
            des: 'El W3C Markup Validation Service, o Servicio de validación de marcado del W3C es un validador creado por el W3C que permite a los usuarios analizar documentos HTML y XHTML bien-formados y válidos. La validación del marcado es un paso importante para asegurar la calidad técnica de las páginas web.​',
          },
          {
            name: 'Caninclude',
            url: 'https://caninclude.glitch.me/',
            id: 'Dev-2',
            category: 'HTML',
            des: 'Puedo incluir - Bienvenido - ¿Puedo incluir una etiqueta hija a una etiqueta padre? Hijo.',
          },
          {
            name: 'HTML Reference',
            url: 'https://htmlreference.io/',
            id: 'Dev-3',
            category: 'HTML',
            des: 'Una guía gratuita de HTML. Aprende con el ejemplo: htmlreference.io es una guía gratuita de HTML. Presenta todos los elementos y atributos.',
          },
        ],
        CSS: [
          {
            name: 'Fresh backgrounds gradients',
            url: 'https://webgradients.com/',
            id: 'Dev-3',
            category: 'CSS',
            des: 'Ven a WebGradients.com para ver 180 bonitos degradados line ales en CSS3, Photoshop y Sketch. Esta colección está comisariada por los mejores diseñadores y es totalmente gratuita.',
          },
          {
            name: 'Clip path generator',
            url: 'https://bennettfeely.com/clippy/',
            id: 'Dev-4',
            category: 'CSS',
            des: 'La propiedad clip-path permite crear formas complejas en CSS recortando un elemento a una forma básica (círculo, elipse, polígono o inserto), o a un SVG.',
          },
          {
            name: 'CSS Reference',
            url: 'https://cssreference.io/',
            id: 'Dev-5',
            category: 'CSS',
            des: 'CSS Reference es una guía visual gratuita de CSS. Presenta las propiedades más populares y las explica con ejemplos ilustrados y animados.',
          },
        ],
        Hosting: [
          {
            name: 'Vercel',
            url: 'https://vercel.com/',
            id: 'Dev-5',
            category: 'Hosting',
            des: 'Vercel es la nube de frontend. Construye, escala y asegura una web más rápida y personalizada. - Lo mejor de la Web - Despliegues conectados a Git - Preproducción colaborativa.',
          },
          {
            name: 'Netlify',
            url: 'https://www.netlify.com/',
            id: 'Dev-6',
            category: 'Hosting',
            des: 'Netlify Connect es una capa de unificación de datos que ofrece a los equipos web la libertad de crear sitios web, tiendas en línea y aplicaciones de primera clase con datos procedentes de cualquier fuente.',
          },
        ],
        JavaScript: [
          {
            name: 'The Modern JavaScript Tutorial',
            url: 'https://javascript.info/',
            id: 'Dev-7',
            category: 'JavaScript',
            des: 'Tutorial moderno de JavaScript: explicaciones sencillas pero detalladas con ejemplos y tareas, que incluyen: cierres, documentos y eventos, programación orientada a objetos.',
          },
          {
            name: 'JS Bin',
            url: 'https://jsbin.com/suzatunowo/edit?js,output',
            id: 'Dev-8',
            category: 'JavaScript',
            des: 'Un pastebin en vivo para HTML, CSS & JavaScript y una gama de procesadores, incluyendo SCSS, CoffeeScript, Jade y más..',
          },
        ],
      },
    },
  },
  {
    params: { resources: 'resources-design' },
    props: {
      title: 'JaviRecursos | Herramientas para diseñadores',
      description:
        'En este apartado de la web JaviRecursos, conseguirás herramientas y recursos que te ayuden a diseñar con mayor facilidad y comodidad.',
      keywords: [
        'JaviRecursos | Herramientas para diseñadores',
        'Herramientas para diseñadores',
        'Recursos para diseñadores',
        'Recursos',
        'Diseñadores',
      ],
      id: 'diseño',
      category: true,
      resources: {
        colores: [
          {
            name: 'coolors',
            des: 'Cree la paleta perfecta o inspírese en miles de bellas combinaciones de colores. ',
            url: 'https://coolors.co/',
            id: 'D-1',
            category: 'Colores',
          },
          {
            name: 'Color Hunt',
            des: 'Descubra las nuevas paletas seleccionadas a mano de Color Hunt',
            url: 'https://colorhunt.co/',
            id: 'D-2',
            category: 'Colores',
          },
          {
            name: 'Happy Hues',
            des: '¿No está seguro de qué colores utilizar en sus diseños o dónde utilizarlos? Happy Hues es un sitio de inspiración de paletas de colores que sirve de ejemplo real de cómo utilizar los colores en tus proyectos de diseño.',
            url: 'https://www.happyhues.co/',
            id: 'D-3',
            category: 'Colores',
          },
        ],
        Imágenes: [
          {
            url: 'https://unsplash.com/',
            name: 'Unplash',
            des: 'Imágenes y fotos bonitas y gratuitas que puedes descargar y utilizar para cualquier proyecto. Mejor que cualquier libre de regalías o fotos de archivo.',
            category: 'Imágenes',
            id: 'D-4',
          },
          {
            url: 'https://www.freepik/',
            name: 'Freepik',
            des: 'Millones de recursos gráficos gratis. ✓ Fotos ✓ Imágenes con IA ✓ Vectores ✓ Plantillas ✓ Vídeos. Descubre nuestro generador de creaciones artísticas...',
            id: 'D-5',
            category: 'Imágenes',
          },
          {
            url: 'https://lovepik.com/',
            name: 'Love Pik',
            des: 'Lovepik.com proporciona millones de Imágenes PNG gratuitas, fotos de fondo, ilustraciones, vídeos y plantillas de diseño para diseñadores.',
            id: 'D-6',
            category: 'Imágenes',
          },
          {
            url: 'https://vecteezy.com/',
            name: 'Vecteezy',
            des: 'Explora millones de vectores, Imágenes, fotos y vídeos libres de derechos! Encuentre el gráfico, fondo, clip art, o ícono perfecto para su diseño.',
            id: 'D-7',
            category: 'Imágenes',
          },
          {
            url: 'https://www.pexels.com/',
            name: 'Pexels',
            des: 'Fotos y vídeos de stock gratis que puedes usar donde quieras. Busca millones de Imágenes de stock de alta calidad y libres de regalías.',
            id: 'D-8',
            category: 'Imágenes',
          },
          {
            url: 'https://pixabay.com/',
            name: 'Pixabay',
            des: 'Pixabay es una vibrante comunidad de creativos que comparten Imágenes, vídeos, audio y otros medios libres de derechos. Todo el contenido es liberado por *Pixabay* bajo la Content...',
            id: 'D-9',
            category: 'Imágenes',
          },
        ],
        iconos: [
          {
            url: 'https://www.flaticon.es/',
            name: 'Flaticon',
            id: 'D-10',
            des: 'Los iconos de interfaz gratuitos y en formato SVG más buscados. Más de 24,300 iconos de interfaz gratuitos en 9 estilos diferentes. Son completamente editables.',
            category: 'iconos',
          },
          {
            url: 'https://boxicons.com/',
            name: 'Box icons',
            id: 'D-11',
            des: 'Boxicons es una colección gratuita de iconos de código abierto cuidadosamente elaborados. Cada icono está diseñado en una cuadrícula de 24px con las directrices del material.',
            category: 'iconos',
          },
          {
            url: 'https://www.iconfinder.com/',
            name: 'Icons Finder',
            des: 'Iconfinder es el mayor mercado del mundo de iconos, ilustraciones e ilustraciones 3D en formato SVG, AI y PNG.',
            id: 'D-12',
            category: 'iconos',
          },
          {
            url: 'https://devicon.dev/',
            name: 'Devicon',
            des: 'Devicon es un conjunto de iconos que representan lenguajes de programación, diseño y herramientas de desarrollo. Puede utilizarlo como fuente o copiar/pegar directamente el código SVG.',
            id: 'D-13',
            category: 'iconos',
          },
          {
            url: 'https://feathericons.com/',
            name: 'Feather',
            des: 'Feather es una colección de iconos de código abierto de gran belleza. Cada icono está diseñado en una cuadrícula de 24x24 con un énfasis en la simplicidad, la coherencia y la calidad.',
            id: 'D-14',
            category: 'iconos',
          },
          {
            url: 'https://pixelarticons.com/',
            name: 'Pixel articons',
            des: '480 iconos de código abierto de estilo pixel-art, en un color y hechos con una cuadrícula de 24x24px por Gerrit Halfmann. ¡Versión Pro con 1920 iconos con 3 variantes!',
            id: 'D-15',
            category: 'iconos',
          },
          {
            url: 'https://iconos8.es/',
            name: 'Icons 8',
            des: 'Descarga elementos de diseño gratis: iconos, fotos, ilustraciones vectoriales y música para tus videos. Todos los recursos hechos por diseñadores → calidad.',
            id: 'D-16',
            category: 'iconos',
          },
          {
            url: 'https://www.svgrepo.com/',
            name: 'Svg repo',
            des: 'Vectores e iconos gratis en formato SVG. ✓ Descarga gratis vectores mono o multicolor para uso comercial. Buscar en 500.000+ Vectores e Iconos SVG Gratis.',
            id: 'D-17',
            category: 'iconos',
          },
        ],
        'Otros...': [
          {
            url: 'https://colourcontrast.cc/',
            name: 'Colour Contrast Checker',
            id: 'D-18',
            des: 'Compruebe el contraste entre las distintas combinaciones de Colores según las normas WCAG.',
            category: 'Otros...',
          },
          {
            url: 'https://color.adobe.com/es/create/color-contrast-analyzer',
            name: 'Color adobe',
            id: 'D-19',
            des: 'Es posible utilizar la rueda de colores como generador de colores. Como alternativa, puedes extraer paletas o degradados de colores a partir de las Imágenes',
            category: 'Otros...',
          },
          {
            url: 'https://squoosh.app/',
            name: 'Squoosh',
            id: 'D-20',
            category: 'Otros...',
            des: 'Squoosh es el optimizador de Imágenes definitivo que te permite comprimir y comparar Imágenes con distintos códecs en tu navegador.',
          },
          {
            url: 'https://www.upscale.media/',
            name: 'Upscale Image',
            id: 'D-21',
            category: 'Otros...',
            des: 'Mejora la calidad de las fotos con el mejorador de resolución de Imágenes AI de Upscale.media convierte Imágenes de baja calidad en obras maestras de alta definición en cuestión de segundos. Sin esfuerzo',
          },
          {
            url: 'https://compressor.io/',
            name: 'Comprensor.io',
            id: 'D-22',
            category: 'Otros...',
            des: 'Optimiza y comprime Imágenes JPEG, PNG, SVG, GIF y WEBP en línea. Comprime, redimensiona y cambia el nombre de tus fotos gratis.',
          },
          {
            url: 'https://www.remove.bg/',
            name: 'Removebg',
            id: 'D-23',
            category: 'Otros...',
            des: 'Quita el fondo de Imágenes de forma fácil para crear fondos transparentes en PNG ¡GRATIS!',
          },
          {
            url: 'https://tinyjpg.com/',
            name: 'Tiny JPG',
            id: 'D-24',
            category: 'Otros...',
            des: 'Compresor de Imágenes online gratuito para sitios web más rápidos Reduzca el tamaño de archivo de sus Imágenes WEBP, JPEG y PNG con el motor de compresión con pérdida inteligente de TinyPNG.',
          },
        ],
      },
    },
  },
  {
    params: { resources: 'resources-practice' },
    props: {
      title: 'JaviRecursos | Paginas para practicar programación',
      description:
        'En este apartado, conseguirás lugares en donde puedas practicar tu lógica de programación',
      id: 'Practices',
      category: false,
      keywords: [
        'Lógica',
        'Programación',
        'JaviRecursos',
        'Practicar programación',
        'Practicar lógica',
        'Recursos para practicar',
      ],
      resources: [
        {
          name: 'Hacker Rank',
          des: 'HackerRank es la solución de entrevistas y pruebas de codificación líder del mercado para la contratación de desarrolladores. ¡Empieza a contratar al ritmo de la innovación!',
          url: 'https://www.hackerrank.com/',
          id: 'P-1',
        },
        {
          name: 'LeetCode',
          des: 'Mejora tus conocimientos de programación y consigue trabajo rápidamente. Este es el mejor lugar para ampliar tus conocimientos y prepararte para tu próxima entrevista.',
          url: 'https://leetcode.com/',
          id: 'P-2',
        },
        {
          name: 'Coderbyte',
          des: '¿Es usted un desarrollador que se prepara para una entrevista o quiere mejorar sus conocimientos de programación? Obtenga más información.',
          url: 'https://coderbyte.com/',
          id: 'P-3',
        },
        {
          name: 'Edabit',
          des: 'Nuestros pequeños desafíos son un atajo en el laberinto de aprender a programar. Gana XP, desbloquea logros y sube de nivel.',
          url: 'https://edabit.com/',
          id: 'P-4',
        },
      ],
    },
  },
];
